// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUaQ5J9M7cdO3wB64olneJebFB9h25H8M',
    appId: '1:332591432060:web:a5685759c72ccbfa02e4f9',
    messagingSenderId: '332591432060',
    projectId: 'footballapp-5ee50',
    authDomain: 'footballapp-5ee50.firebaseapp.com',
    storageBucket: 'footballapp-5ee50.appspot.com',
    measurementId: 'G-XVK3EJ3EJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh0toYeL2oKC_y75Jfu_VnboIDawWITyg',
    appId: '1:332591432060:android:8a4de6b043126ba502e4f9',
    messagingSenderId: '332591432060',
    projectId: 'footballapp-5ee50',
    storageBucket: 'footballapp-5ee50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfZGf8CfXIGCgIUo8FwUR8HmdGfUk5oPw',
    appId: '1:332591432060:ios:078771a7c0032f8202e4f9',
    messagingSenderId: '332591432060',
    projectId: 'footballapp-5ee50',
    storageBucket: 'footballapp-5ee50.appspot.com',
    iosBundleId: 'com.example.footballScoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfZGf8CfXIGCgIUo8FwUR8HmdGfUk5oPw',
    appId: '1:332591432060:ios:1e7ddf610e61b6f002e4f9',
    messagingSenderId: '332591432060',
    projectId: 'footballapp-5ee50',
    storageBucket: 'footballapp-5ee50.appspot.com',
    iosBundleId: 'com.example.footballScoreApp.RunnerTests',
  );
}
